services:
  - type: web
    name: darjeeling-momos-server
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_EMAIL_PASSWORD
        sync: false
      - key: CLIENT_URL
        value: https://darjeeling-momos-client.onrender.com
      - key: JWT_SECRET
        sync: false

  - type: web
    name: darjeeling-momos-client
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://darjeeling-momos-server.onrender.com/api
